#!/usr/bin/env python3
"""
Generate a pssh hosts file from terraform output JSON.

Usage:
    terraform -chdir=../terraform output -json | python3 gen_pssh_hosts.py > pssh_hosts

    Then:
    pssh -h pssh_hosts -l ubuntu -x "-i ~/.ssh/rabbitmq_ed25519 -o StrictHostKeyChecking=no" -i <command>

Expected terraform outputs:
    public_ips — map of node name → public IP
"""

import json
import sys


def main() -> None:
    tf = json.loads(sys.stdin.read())
    public_ips: dict[str, str] = tf["public_ips"]["value"]

    lines = ["# Generated by scripts/gen_pssh_hosts.py — do not edit manually."]
    for node in sorted(public_ips):
        lines.append(f"ubuntu@{public_ips[node]}")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
