#!/usr/bin/env python3
"""
Generate Ansible inventory YAML from terraform output JSON.

Usage:
    terraform -chdir=../terraform output -json | python3 gen_inventory.py > ../ansible/inventory/hosts.yml

Expected terraform outputs:
    public_ips  — map of node name → public IP
    private_ips — map of node name → private IP
"""

import json
import sys

import yaml


def main() -> None:
    raw = sys.stdin.read()
    tf = json.loads(raw)

    public_ips: dict[str, str] = tf["public_ips"]["value"]
    private_ips: dict[str, str] = tf["private_ips"]["value"]

    seed = "rabbitmq-1"
    nodes = sorted(k for k in public_ips if k != seed)

    inventory = {
        "all": {
            "children": {
                "rabbitmq_all": {
                    "children": {
                        "rabbitmq_seed": {
                            "hosts": {
                                seed: {
                                    "ansible_host": public_ips[seed],
                                    "private_ip": private_ips[seed],
                                }
                            }
                        },
                        "rabbitmq_nodes": {
                            "hosts": {
                                node: {
                                    "ansible_host": public_ips[node],
                                    "private_ip": private_ips[node],
                                }
                                for node in nodes
                            }
                        },
                    },
                    "vars": {
                        "ansible_user": "ubuntu",
                        "ansible_ssh_private_key_file": "~/.ssh/rabbitmq_ed25519",
                        "ansible_ssh_common_args": "-o StrictHostKeyChecking=no",
                    },
                }
            }
        }
    }

    print("# Generated by scripts/gen_inventory.py — do not edit manually.")
    print(yaml.dump(inventory, default_flow_style=False, sort_keys=False))


if __name__ == "__main__":
    main()
