#!/usr/bin/env python3
"""
Generate Ansible inventory for the test client.

Reads test client Terraform output from stdin, and the RabbitMQ cluster
Terraform output from --rabbitmq-tf-dir. Injects the cluster private IPs
as a group var (rabbitmq_hosts) so Ansible templates can render them.

Usage:
    cd test
    terraform -chdir=terraform output -json | \\
        python3 scripts/gen_inventory.py --rabbitmq-tf-dir ../terraform \\
        > ansible/inventory/hosts.yml
"""

import argparse
import json
import subprocess
import sys

import yaml


def get_tf_outputs(chdir: str) -> dict:
    result = subprocess.run(
        ["terraform", f"-chdir={chdir}", "output", "-json"],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--rabbitmq-tf-dir",
        default="../terraform",
        help="Path to the RabbitMQ cluster Terraform directory",
    )
    args = parser.parse_args()

    test_tf = json.loads(sys.stdin.read())
    public_ip: str = test_tf["public_ip"]["value"]
    private_ip: str = test_tf["private_ip"]["value"]

    rmq_tf = get_tf_outputs(args.rabbitmq_tf_dir)
    rmq_private_ips: list[str] = sorted(rmq_tf["private_ips"]["value"].values())

    inventory = {
        "all": {
            "children": {
                "test_clients": {
                    "hosts": {
                        "rabbitmq-test-client": {
                            "ansible_host": public_ip,
                            "private_ip": private_ip,
                        }
                    },
                    "vars": {
                        "ansible_user": "ubuntu",
                        "ansible_ssh_private_key_file": "~/.ssh/rabbitmq_ed25519",
                        "ansible_ssh_common_args": "-o StrictHostKeyChecking=no",
                        "rabbitmq_hosts": rmq_private_ips,
                    },
                }
            }
        }
    }

    print("# Generated by scripts/gen_inventory.py — do not edit manually.")
    print(yaml.dump(inventory, default_flow_style=False, sort_keys=False))


if __name__ == "__main__":
    main()
